ukui/ukui-search

debian/ukui-search.install
=> modified debian/ukui-search.install

libsearch/index/construct-document.cpp, libsearch/index/index-generator.cpp, libsearch/index/inotify-index.cpp
[FIX] File index won't be created correctly when copied a folder which has many childern folders
=> [FIX] File index won't be created correctly when copied a folder which has many childern folders

src/content-widget.cpp, src/control/home-page-item.cpp, src/control/search-detail-view.cpp
Description: 修复主页面最近打开列表文件显示和排版有误的问题
=> fix(frontend): Recently opened files displayed incorrectly in homepage.

debian/control, libsearch/global-settings.h, src/content-widget.cpp, src/content-widget.h, src/control/search-detail-view.cpp, src/control/search-detail-view.h, src/control/search-list-view.cpp, src/control/search-list-view.h, src/mainwindow.cpp, src/model/search-item.h, src/settings-widget.cpp, src/settings-widget.h, src/src.pro, translations/ukui-search/bo.ts, translations/ukui-search/tr.ts, translations/ukui-search/zh_CN.ts
Description: 添加网页搜索功能和搜索引擎设置功能
=> feat(frontend): Add web searching & web engine settings.

libsearch/appsearch/app-match.cpp, libsearch/appsearch/app-match.h
=> Docking software store

libsearch/appsearch/app-match.cpp, libsearch/appsearch/app-match.h
=> add dir watch of desktop

src/control/search-detail-view.cpp
Description: 修复点击应用安装时ukui-search主进程崩溃的问题
=> fix(frontend): Main process crashed when open kylin-software-center to install applications.

src/content-widget.cpp, src/control/home-page-item.cpp, src/control/home-page-item.h, src/control/search-detail-view.cpp, src/mainwindow.cpp, translations/ukui-search/zh_CN.ts
Description: 根据最新需求调整主界面布局和快速打开应用
新增：呼出主界面，输入框聚焦，可直接输入
=> feat(frontend): Adjust layout & controls for homepage.

libsearch/appsearch/app-match.cpp, libsearch/appsearch/app-match.h, src/main.cpp
=> Application Search Optimization

libsearch/appsearch/app-match.cpp, libsearch/appsearch/app-match.h, src/control/search-detail-view.cpp, src/model/search-item.cpp, src/search-app-thread.cpp, src/search-app-thread.h
=> feat(frontend): Sort installed applications.

libsearch/index/construct-document.cpp, libsearch/index/construct-document.h, libsearch/index/first-index.cpp, libsearch/index/index-generator.cpp, libsearch/index/ukui-search-qdbus.cpp, src/main.cpp
=> [Fix]Index process may crash while system first boot;

libsearch/appsearch/app-match.cpp
http://172.17.66.192/biz/bug-view-42203.html
=> fix:Type a lot of space, and you'll still see a lot of app names

libsearch/appsearch/app-match.cpp, src/control/search-detail-view.cpp, src/control/search-detail-view.h, src/main.cpp, src/search-app-thread.cpp
Log: 修复软件商店打开后点击安装不会再跳转的bug
Bug: http://172.17.66.192/biz/bug-view-41150.html
=> fix(frontend): Software center will not refresh which is already opened.

src/mainwindow.cpp
=> Fix: Fit muti-screens mode.

libsearch/index/pinyinWithTone.txt, libsearch/index/pinyinWithoutTone.txt, src/mainwindow.cpp
Description: 重新计算搜索主界面的显示位置
Log: 重新计算搜索主界面的显示位置
=> feat(frontend): Reset geometry for ukui-search.

libsearch/settingsearch/setting-match.cpp, libsearch/settingsearch/setting-match.h
=> fix:Sets polyphonic and English questions when searching

libsearch/global-settings.cpp, libsearch/global-settings.h, src/control/highlight-item-delegate.cpp, src/control/home-page-item.cpp, src/control/home-page-item.h, src/control/search-list-view.cpp, src/custom-style.cpp, src/custom-style.h, src/src.pro
修复字体大小改变时搜索结果列表行高和fontmetircs不刷新的bug.
=> Fix: Font-size & row height will not refresh in search list.

data/org.ukui.search.data.gschema.xml, debian/ukui-search.install, src/mainwindow.cpp, src/mainwindow.h, src/settings-widget.cpp, src/settings-widget.h
=> Feature:Add web-engine settings key.

data/org.ukui.log4qt.ukui-search.gschema.xml, src/src.pro
=> Feature: Add log gsettings for ukui-search.

libsearch/appsearch/app-match.cpp
link:172.17.66.192/biz/bug-view-49153.html
=> fix:can not search android app

src/mainwindow.cpp, src/mainwindow.h
=> Start ukui-control-center on settings button clicked.

src/content-widget.cpp, src/control/search-list-view.cpp, src/control/search-list-view.h, src/create-index-ask-dialog.cpp, src/mainwindow.cpp, src/mainwindow.h, src/model/search-item-model.cpp, src/model/search-item-model.h, src/search-app-thread.cpp
=> fix(frontend): UI for search list & dialog will not refresh when font size changed.

libchinese-segmentation/chinese-segmentation.cpp, libsearch/global-settings.cpp, libsearch/global-settings.h, libsearch/plugininterface/search-plugin-iface.h, src/content-widget.cpp, src/control/highlight-item-delegate.cpp, src/control/highlight-item-delegate.h, src/control/home-page-item.cpp, src/control/search-detail-view.cpp, src/control/search-detail-view.h, src/control/search-list-view.cpp, src/create-index-ask-dialog.cpp, src/create-index-ask-dialog.h, src/main.cpp, src/mainwindow.cpp, src/mainwindow.h, src/model/search-item-model.cpp, src/model/search-item-model.h, src/settings-widget.cpp, src/settings-widget.h
修复了一些代码漏洞
修复收到palettechanged信号时列表选中状态消失的问题
统一窗口标题，修改部分头文件引用位置
修复主题图标改变时详情页图标未更新的问题.
添加部分编译选项
=> Optimize code

libsearch/settingsearch/setting-match.cpp
link:172.17.66.192/biz/bug-view-48908.html
=> fix:Night mode can be search in huawei

frontend/control/stack-pages/search-page-section.cpp, frontend/control/stack-pages/search-page-section.h, frontend/control/stack-pages/search-page.cpp, frontend/control/stack-pages/search-page.h, frontend/control/stacked-widget.cpp, frontend/control/stacked-widget.h, frontend/mainwindow.cpp, frontend/model/search-result-manager.cpp, frontend/model/search-result-model.cpp, frontend/model/search-result-model.h, frontend/view/result-view.cpp, frontend/view/result-view.h
Description: 完善重构版前端部分原有功能，如字体适配、展开收起、历史记录、右键菜单等
=> feat(frontend): Complete some functions of new frontend.
